name = "rancang"
main = ".output/server/index.mjs"
account_id = ""
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "a992842f2531437ea6d08e3dff284ecd"

[[r2_buckets]]
binding = "UPLOADS_R2"
bucket_name = "rancang-uploads"

[assets]
directory = ".output/public"

