name = "rancang"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "a992842f2531437ea6d08e3dff284ecd"

[[r2_buckets]]
binding = "UPLOADS_R2"
bucket_name = "rancang-uploads"

[vars]
CONTACT_WEBHOOK_URL = ""
